spring.application.name=apachecamelstudyA
spring.activemq.broker-url=tcp://localhost:61616
camel.component.kafka.brokers=localhost:9092

endpoint-for-logging=log:something
timePeriod=3000

# Enable these logging levels to see more detailed Apache Camel logs
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG